### ISSUE TITLE
Bundle correct go-ipfs version when generating the bundle

### ISSUE THREAD

**Issue by kyledrake** [ipfs-shipyard/ipfs-station#68]
With Ubuntu 15.04:

```
~/Downloads/Station-linux-x64 $ ./Station 
info: Booting
info: Application is ready
info: Starting tray
Uncaught Error: non-zero exit code 2
  while running: /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/subcomandante/subcom 7894 /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs version

  /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs: 1: /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs: Syntax error: "(" unexpected

    at ChildProcess.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/subcomandante/fork.js:21:23)
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
    at <error: TypeError: Cannot read property 'name' of undefined>
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at Stream.object.(anonymous function) [as on] (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at Object.module.exports.version (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/ipfsd-ctl/index.js:175:8)
    at onRequestState (/home/kyle/Downloads/Station-linux-x64/resources/app/build/init.js:74:25)
    at EventEmitter.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/electron-safe-ipc/protocol.js:25:18
    at /home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33
    at doNTCallback0 (node.js:419:9)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at EventEmitter.object.(anonymous function) [as on] (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at startTray (/home/kyle/Downloads/Station-linux-x64/resources/app/build/init.js:156:7)
    at EventEmitter.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/build/init.js:257:7)
    at EventEmitter.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.appReady (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/menubar/index.js:63:13)
    at EventEmitter.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitOne (events.js:82:20)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at EventEmitter.object.(anonymous function) [as on] (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at /home/kyle/Downloads/Station-linux-x64/resources/app/build/init.js:241:8
    at Object.module.exports.local (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/ipfsd-ctl/index.js:186:5)
    at Object.boot (/home/kyle/Downloads/Station-linux-x64/resources/app/build/init.js:236:25)
    at EventEmitter.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Server.handleListening (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/monogamous/dist/monogamous.js:65:23)
    at Server.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
    at EventEmitter.object.(anonymous function) [as on] (/home/kyle/Downloads/Station-linux-x64/resources/app/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
    at Object.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/app/index.js:29:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/atom.asar/browser/lib/init.js:123:10)
    at Object.<anonymous> (/home/kyle/Downloads/Station-linux-x64/resources/atom.asar/browser/lib/init.js:125:4)
    at Module._compile (module.js:434:26)
Uncaught undefined
Uncaught undefined
error: Uncaught Exception
```

**Comment by Dignifiedquire** [comment]
ping @jbenet I don't have  linux machine around atm and it sounds like it's an issue with the forking again :(

**Comment by ion1** [comment]
```
Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs: Mach-O 64-bit x86_64 executable
```

When Linux doesn’t understand the executable file format, it tries to run it through sh, resulting in the confusing syntax error. From strace:

```
18293 execve("/tmp/foo/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs", ["/tmp/foo/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs", "daemon"], [/* 121 vars */] <unfinished ...>
18293 execve("/bin/sh", ["/bin/sh", "/tmp/foo/Station-linux-x64/resources/app/node_modules/go-ipfs/bin/ipfs", "daemon"], [/* 121 vars */] <unfinished ...>
```

**Comment by Dignifiedquire** [comment]
@ion1 might that be that the go-ipfs binary packaged on my osx is not compatible with linux?

**Comment by jbenet** [comment]
need to package the right binary for the right platform. `npm install go-ipfs` does this correctly for your local arch. maybe https://github.com/ipfs/npm-go-ipfs should expose a function to be able to install a specific go-platform.
